### ISSUE TITLE
time_t does not name a type compile error on Ardunio 1.5.6-r2

### ISSUE THREAD

**Issue by ghost** [akafugu/VFDDeluxe#1]
Compiling fails withe the following error messages:

Arduino: 1.5.6-r2 (Windows 7), Board: "Akafuino L"

gps.cpp:50: error: 'time_t' does not name a type
gps.cpp:54: error: variable or field 'setRTCTime' declared void
gps.cpp:54: error: 'time_t' was not declared in this scope
gps.cpp: In function 'void parseGPSdata(char*)':
gps.cpp:155: error: 'time_t' was not declared in this scope
gps.cpp:155: error: expected `;' before 'tNow'
gps.cpp:219: error: 'tNow' was not declared in this scope
gps.cpp:219: error: 'class WireRtcLib' has no member named 'makeTime'
gps.cpp:222: error: 'tLast' was not declared in this scope
gps.cpp:228: error: 'tDelta' was not declared in this scope
gps.cpp:234: error: 'SECS_PER_HOUR' was not declared in this scope
gps.cpp:239: error: 'setRTCTime' was not declared in this scope
gps.cpp:265: error: 'tLast' was not declared in this scope
gps.cpp:265: error: 'tNow' was not declared in this scope

The Time, TimeAlarms, DS1307RTC ,UDPbitewise, and akafugu libraries are installed, and I'm using Ardunio 1.5.6-r2.

**Comment by perjg** [comment]
The latest VFDDeluxe FW relies on new functionality in ds_rtc_lib.
(specifically, the addition of makeTime/breakTime functionality)
Could you please double-check that you have the latest version and try
again.

On Tue, May 13, 2014 at 10:29 AM, Scott Wilson notifications@github.comwrote:

> Compiling fails withe the following error messages:
> 
> Arduino: 1.5.6-r2 (Windows 7), Board: "Akafuino L"
> 
> gps.cpp:50: error: 'time_t' does not name a type
> gps.cpp:54: error: variable or field 'setRTCTime' declared void
> gps.cpp:54: error: 'time_t' was not declared in this scope
> gps.cpp: In function 'void parseGPSdata(char*)':
> gps.cpp:155: error: 'time_t' was not declared in this scope
> gps.cpp:155: error: expected `;' before 'tNow'
> gps.cpp:219: error: 'tNow' was not declared in this scope
> gps.cpp:219: error: 'class WireRtcLib' has no member named 'makeTime'
> gps.cpp:222: error: 'tLast' was not declared in this scope
> gps.cpp:228: error: 'tDelta' was not declared in this scope
> gps.cpp:234: error: 'SECS_PER_HOUR' was not declared in this scope
> gps.cpp:239: error: 'setRTCTime' was not declared in this scope
> gps.cpp:265: error: 'tLast' was not declared in this scope
> gps.cpp:265: error: 'tNow' was not declared in this scope
> 
> The Time, TimeAlarms, DS1307RTC ,UDPbitewise, and akafugu libraries are
> installed, and I'm using Ardunio 1.5.6-r2.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akafugu/VFDDeluxe/issues/1
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by ghost** [comment]
The updated libary worked, but it's now failing at:

Arduino: 1.5.6-r2 (Windows 7), Board: "Akafuino L"

C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:79: error: 'USB_VID' was not declared in this scope
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:79: error: 'USB_PID' was not declared in this scope
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:82: error: 'USB_VID' was not declared in this scope
C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:82: error: 'USB_PID' was not declared in this scope

**Comment by perjg** [comment]
Our boards.txt file hasn't really been tested with 1.5 yet. I'll try and
see if I can reproduce the issue.

On Tue, May 13, 2014 at 12:07 PM, Scott Wilson notifications@github.comwrote:

> The updated libary worked, but it's now failing at:
> 
> Arduino: 1.5.6-r2 (Windows 7), Board: "Akafuino L"
> 
> C:\Program Files
> (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:79: error:
> 'USB_VID' was not declared in this scope
> C:\Program Files
> (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:79: error:
> 'USB_PID' was not declared in this scope
> C:\Program Files
> (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:82: error:
> 'USB_VID' was not declared in this scope
> C:\Program Files
> (x86)\Arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp:82: error:
> 'USB_PID' was not declared in this scope
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/akafugu/VFDDeluxe/issues/1#issuecomment-42912801
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by perjg** [comment]
The FW should work with our latest libraries now.
