### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by lawrenceloyd** [akafugu/VFDDeluxe#2]
display.cpp: In function 'void set_brightness(uint8_t)':
display.cpp:227: error: 'TC4H' was not declared in this scope
display.cpp:228: error: 'OCR4D' was not declared in this scope
display.cpp:229: error: 'TCNT4' was not declared in this scope
display.cpp: In function 'void detect_shield()':
display.cpp:287: error: 'extra1' is not a member of 'PinMap'
display.cpp:288: error: 'extra2' is not a member of 'PinMap'
display.cpp:289: error: 'extra1' is not a member of 'PinMap'
display.cpp:290: error: 'extra2' is not a member of 'PinMap'
display.cpp: In function 'void set_dimming(bool)':
display.cpp:397: error: 'TC4H' was not declared in this scope
display.cpp:398: error: 'OCR4D' was not declared in this scope
display.cpp: In function 'void write_vfd_iv17_6d(uint8_t, uint16_t)':
display.cpp:994: error: 'extra1' is not a member of 'PinMap'
display.cpp:995: error: 'extra2' is not a member of 'PinMap'
display.cpp:999: error: 'extra1' is not a member of 'PinMap'
display.cpp:1000: error: 'extra2' is not a member of 'PinMap'
display.cpp:1004: error: 'extra1' is not a member of 'PinMap'
display.cpp:1005: error: 'extra2' is not a member of 'PinMap'
display.cpp: In function 'void __vector_9()':
display.cpp:1248: error: 'TC4H' was not declared in this scope
display.cpp:1249: error: 'OCR4D' was not declared in this scope
display.cpp:1254: error: 'TC4H' was not declared in this scope
display.cpp:1255: error: 'OCR4D' was not declared in this scope

**Comment by perjg** [comment]
This happens when the board is not set properly in the menu before compiling.

It looks like you are trying to compile for atmega328p, which hasn't been tested in a long time, and isn't really supported.

If you want to build for the normal VFD Modular Clock v2.X base board, set the board to "Akafuino L" and then try again. See here for installation instructions: http://www.akafugu.jp/posts/products/akafuino_l/installation/

**Comment by lawrenceloyd** [comment]
When I try to compile with leonardo or akafuin L I get this.

gps.cpp:50: error: 'time_t' does not name a type
gps.cpp:54: error: variable or field 'setRTCTime' declared void
gps.cpp:54: error: 'time_t' was not declared in this scope
gps.cpp: In function 'void parseGPSdata(char*)':
gps.cpp:155: error: 'time_t' was not declared in this scope
gps.cpp:155: error: expected `;' before 'tNow'
gps.cpp:219: error: 'tNow' was not declared in this scope
gps.cpp:219: error: 'class WireRtcLib' has no member named 'makeTime'
gps.cpp:222: error: 'tLast' was not declared in this scope
gps.cpp:228: error: 'tDelta' was not declared in this scope
gps.cpp:234: error: 'SECS_PER_HOUR' was not declared in this scope
gps.cpp:239: error: 'setRTCTime' was not declared in this scope
gps.cpp:265: error: 'tLast' was not declared in this scope
gps.cpp:265: error: 'tNow' was not declared in this scope

Also, the schematic is for the 328p, I have both the uno and leonardo, if the 32u4 is the preferred IC what are the output pins to the HV5812. Will this work with the leonardo?

**Comment by lawrenceloyd** [comment]
Ok, I finally got it to compile and upload to the Leonardo. I'm confused on the connections to the HV5812 as the only schematic you have is for the 328p. Also is the board supposed to be blinking an led to signify time keeping.

**Comment by perjg** [comment]
Not sure if this is relevant any longer, but we now have schematics for the 32u4 board too: http://www.akafugu.jp/posts/products/vfd-modular-clock/resources/
