### ISSUE TITLE
error valve

### ISSUE THREAD

**Issue by galeots** [akafugu/VFDDeluxe#4]
I built the clock by only copying the project, but when does the clock time positions are wrong! I I run that SHIELD I wrong. Correct would 1-2-3-4-5-6 but laddered so 2-1-4-3-6-5 then the signals are not good.
This can be remedied by program !?

**Comment by perjg** [comment]
Please see the file display.cpp, it contains mappings for all the supported shields.

If your custom display is wired up in a different order (grids or segments), you will need to adjust this file.
