### ISSUE TITLE
install library eeprom

### ISSUE THREAD

**Issue by galeots** [akafugu/VFDDeluxe#5]
hepl for install library eeprom, my not use eeprom for library word letter generation

**Comment by perjg** [comment]
Sorry for missing this issue. There are instructions on how to program the EEPROM chip here: http://www.akafugu.jp/posts/blog/2012_02_29%20-%20Four%20Letter%20Word%20Generator%20PART%202%20-%20EEPROM%20Programmer/

If your order came with a faulty EEPROM chip that doesn't work for FLW, please email us with your order number and we will provide a replacement.
